images:
  - name: springcloud/spring-cloud-skipper-server  # used for Kustomize matching
    newName: springcloud/spring-cloud-skipper-server
    newTag: 2.4.0.BUILD-SNAPSHOT
configMapGenerator:
- name: skipper
  files:
    - application.yaml
bases:
  - ../../base
patches:
- deployment-patch.yaml
- service-patch.yaml
