# TODO better name for secret being used
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper
spec:
  template:
    spec:
      containers:
        - name: skipper
          volumeMounts:
            - name: database
              mountPath: /etc/secrets/database
              readOnly: true
      volumes:
        - name: database
          secret:
            secretName: mysql
