images:
  - name: springcloud/spring-cloud-dataflow-server  # used for Kustomize matching
    newName: springcloud/spring-cloud-dataflow-server
    newTag: 2.5.0.BUILD-SNAPSHOT
configMapGenerator:
- name: scdf-server
  files:
    - application.yaml
bases:
  - ../../base
patches:
- deployment-patch.yaml
- service-patch.yaml

